# Generated by Django 2.0.1 on 2018-01-24 08:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default=None, help_text='Title', max_length=200)),
                ('content', models.CharField(blank=True, default=None, help_text='Content', max_length=99999)),
            ],
        ),
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, default=None, help_text='username', max_length=200)),
                ('firstName', models.CharField(blank=True, default=None, help_text='First Name', max_length=200)),
                ('lastName', models.CharField(blank=True, default=None, help_text='Last Name', max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='article',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Author'),
        ),
    ]
